apiVersion: apps/v1
kind: Deployment
metadata:
  name: set-app
  labels:
    app: set-app
    #tier: db-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: set-app
     # tier: db-service
  template:
    metadata:
      labels:
        app: set-app
        #tier: db-service
    spec:
      containers:
        - name: db-service
          image: roman626/db-service
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: set-service
spec:
  type: ClusterIP
  selector:
    app: set-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  #annotations:
  #  nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /api/all
            pathType: Prefix
            backend:
              service:
                name: set-app
                port:
                  number: 80