name: "set-pipeline"

trigger:
  - master

stages:
  - stage: "Build_test_push"
    displayName: "[STAGE] Compile, build, test application and push images to docker hub"
    jobs:
      - job: "Build_test_push"
        displayName: "[JOB] Compile, build, test application and push images to docker hub"
        pool: "Ubuntu_Poll"
        steps:
          - script: sudo chmod +x gradlew; ./gradlew clean compileTestJava
            displayName: "[SCRIPT] Compile app"
          - script: ./gradlew db-service:test
            displayName: "[SCRIPT] Run unit test for db-service"
          - script: ./gradlew componentTest
            displayName: "[SCRIPT] Run component test"
          - script: ./gradlew runBootJar
            displayName: "[SCRIPT] Build jar"
          - script: sudo chmod +x /usr/bin/docker-compose; sudo docker-compose -f docker-compose.push.yml build;
            displayName: "[SCRIPT] Build images"
          - script: sudo chmod 666 /var/run/docker.sock; docker login -u "roman626" -p "626mabasA626!" docker.io; sudo docker-compose -f docker-compose.push.yml push
            displayName: "[SCRIPT] Push images"

  - stage: "Pull_deploy_integration"
    displayName: "[STAGE] Pull images, deploy and run integration tests"
    jobs:
      - job: "Pull_deploy_integration"
        displayName: "[JOB] Pull images, deploy and run integration tests"
        pool: "Ubuntu_Poll2"
        steps:
          - script: sudo chmod +x /usr/bin/docker-compose; sudo docker-compose -f docker-compose.remote.yml up
            displayName: "[SCRIPT] Pull and deploy images"