name: "set-pipeline"

trigger:
  - master

stages:
  - stage: "Compile_app_and_unit_tests"
    displayName: "[STAGE] Compile application and run unit tests"
    jobs:
      - job: "Compile_app"
        displayName: "[JOB] Compile application"
        pool: "Windows_Pool"
        steps:
          - script: gradle clean build
            displayName: "[SCRIPT] Run gradle clean build"
      - job: "Unit_test"
        displayName: "[JOB] Run unit tests"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: gradle db-service:test
            displayName: "[SCRIPT] Run unit test"
