name: "set-pipeline"

trigger:
  - master

stages:
  - stage: "Build_app_stage"
    displayName: "[STAGE] Run runBootJar gradle task"
    jobs:
      - job: "Build_app_job"
        displayName: "[JOB] Run runBootJar gradle task"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: gradle clean runBootJar
            displayName: '[SCRIPT] Run runBootJar'
