name: "set-pipeline"

trigger:
  - master

stages:
  - stage: "Compile_app_and_unit_tests"
    displayName: "[STAGE] Compile application and run unit tests"
    jobs:
      - job: "Compile_and_test_app"
        workspace:
          clean: all
        displayName: "[JOB] Compile application"
        pool: "Ubuntu_Poll"
        steps:
          - script: chmod +x gradlew; ./gradlew clean compileTestJava
            displayName: "[SCRIPT] Run gradlew clean compileTestJava"
          - script: ./gradlew db-service:test
            displayName: "[SCRIPT] Run unit test"
          - script: ./gradlew componentTest
            displayName: "[SCRIPT] Run component test"
          - script: sudo chmod +x /usr/bin/docker-compose; docker-compose up -d
            displayName: "[SCRIPT] Deploy app"

