name: "set-pipeline"

trigger:
  - master

stages:
  - stage: "Build app stage"
    displayName: "[STAGE] Run runBootRun gradle task"
    jobs:
      - job: "Build app job"
        displayName: "[JOB] Run runBootRun gradle task"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: gradle clean runBootRun
            displayName: '[SCRIPT] Run runBootRun'
