version: "3.5"

networks:
  set-network:
    name: set-network

services:
  config-server:
    build:
      config-server/
    hostname: config-server
    ports:
      - 8888:8888
    networks:
       - set-network

  registration-server:
    build:
      registration-server/
    hostname: registration-server
    ports:
      - 8761:8761
    networks:
      - set-network
    depends_on:
      - config-server

  db-service:
    build:
      db-service/
    hostname: db-service
    ports:
      - 8082:8082
    networks:
      - set-network
    depends_on:
      - config-server
      - registration-server

  validator-service:
    build:
      validator-service/
    hostname: validator-service
    ports:
      - 8083:8083
    networks:
      - set-network
    depends_on:
      - config-server
      - registration-server
      - db-service

  admin-service:
    build: admin-service/
    hostname: admin-service
    ports:
      - 8084:8084
    networks:
      - set-network
    depends_on:
      - config-server
      - registration-server
      - db-service
      - validator-service

  gateway-service:
    build:
      gateway-service/
    hostname: gateway-service
    ports:
      - 8766:8766
    networks:
      - set-network
    depends_on:
      - config-server
      - registration-server
      - db-service
      - validator-service
      - admin-service


