server:
  port: 8084
  error:
    path: /error
    whitelabel:
      enabled: false

spring:
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://registration-server:8761/eureka/, http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      shutdown:
        enabled: true
endpoints:
  shutdown:
    enabled: true

#feign:
#  hystrix:
#    enabled: true