spring:
  application:
    name: gateway-service
server:
  port: 8766

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://registration-server:8761/eureka/, http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

zuul:
  routes:
    db-service:
      serviceId: db-service
    admin-service:
      serviceId: admin-service