server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://registration-server:8761/eureka/, http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      shutdown:
        enabled: true
endpoints:
  shutdown:
    enabled: true